cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'unrar'
brew 'the_silver_searcher'
brew 'python'
brew 'git'
brew 'mas'
brew 'vim'

cask 'atom'
cask 'google-chrome'
cask 'vlc'
cask 'spotify'
cask 'java'
cask 'intellij-idea-ce'
